### ISSUE TITLE
add better handling for lists

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem-Service-Library#5]
Had to use Config.dnsmeta.rdtypes = [item.strip() for item in Config.dnsmeta.rdtypes.split(',')] for dnsmeta. Probably easier just to add this directly to the API.

**Comment by ms-xy** [comment]
This is interesting for the upcoming discussion INI versus json, it is a clear point in favor of json.
That being said, modifying the library to support getting values as arrays from INI files shouldn't be too hard either. In the python config parser it would be not as sleek as for the upcoming Go version (tags on struct fields + reflecting types to find out how to treat the values)

**Comment by ms-xy** [comment]
To be closed by #7 we are switching to JSON configuration files for all services.
