### ISSUE TITLE
Add Core Functionality

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem-Service-Library#6]
We should provide functionality for:

- [ ] Configuration parsing for JSON?
- [ ] Identify type for no file
- [ ] Validate/filter IP
- [ ] Validate/filter Domain
- [ ] Validate/filter Email
- [ ] Info output
- [ ] submit an object for storage

**Comment by ms-xy** [comment]
Working on it.
One question though, do we really want to include submission of objects to Storage in the service library? I thought services ain't supposed to submit anything to Storage by themselves? (plus we already kinda have similar functionality in the toolbox)

**Comment by webstergd** [comment]
Good catch and you are totally correct. So yeah we probably should have totem and totem-dynamic manage object submissions.  i.e. Service returns a code and the objects.

Until we do that, do we want to maybe do a stopgap? We could have a method in the library that allows a Service to directly submit the object to the gateway or storage. Anyway, your call on that. 

The toolbox is completely separate. That is just a handy CLI for using the system. This should be how Services interact.

**Comment by ms-xy** [comment]
I'm always happy to implement stuff ;)
So yeah, for the time being I'll implement something.
